const { SerialPort, ReadlineParser } = require('serialport')
const port = new SerialPort({ path:'COM3', baudRate:115200 })
const parser = port.pipe(new ReadlineParser())
parser.on('data', console.log)
// port.write('ROBOT PLEASE RESPOND\n')